### ISSUE TITLE
Some issues I've found.

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [KoTeuKa404/thaumicforever#1]
Magic dust has a broken item name, and also is used for a infusion that doesn't currently do anything.
![asfdgvvasdfvfavvdabdffghhj](https://github.com/user-attachments/assets/a9567e11-5a32-4843-afdf-fa83d947f1ea)
![asdhdbdbdb dbdffgnfhnghmkkkl](https://github.com/user-attachments/assets/f99e021a-ece6-4abf-b468-24696f8bfddf)
A few researches that look accessible have broken names and contents.
![dasfvdafbvdfabdabbgbngngfnghjjkk](https://github.com/user-attachments/assets/0ff426f8-4d27-4d76-a517-55b61b90613b)
![asdfhdfhadfbdfvdfvafsvsvdfshj](https://github.com/user-attachments/assets/6170a7ce-3f5b-46bf-ac84-f7282ae62105)
Guards also hold weapons wrong.
![asdfgdfvvvdfbvdbdbnm](https://github.com/user-attachments/assets/098385d6-abc0-4e11-abf7-7fb6dbaabae4)
The researches that aren't broken also lack a lot of detail. For example I currently have no idea what the zombie heart amulet does. Also there seems to be a number of things that are not mentioned at all in the mod that I had to go through your change logs to learn about like guards. Cool mod though, you have some neat ideas.

**Comment by xxXCuriositykilledthecatXxx** [comment]
Also it seems like some of your structures are putting out a lot of loot, you might want to lower it a bit. This chest is surrounded by empty ones, so there might be an issue with all the loot being put into one inventory.
![asfdhdfhdbdfvdvsacscdasdcsdfhdbj](https://github.com/user-attachments/assets/a3cf0bc8-16e7-409a-926a-bbb893f25264)

**Comment by xxXCuriositykilledthecatXxx** [comment]
One more thing, This structure is everywhere. It also generates with a random glass block off to the side which I'm sure isn't intentional. Also the generation of these structures create spam in the log.
![1sdafgfsddfvvdasfvdfvdfbbn](https://github.com/user-attachments/assets/44ad4b7c-3163-40e3-b9cc-6cf96380c07b)
![adfbdbbddbdbfgngfnfrnm](https://github.com/user-attachments/assets/3b0876cc-e548-41e7-bf20-914371fd715e)

**Comment by KoTeuKa404** [comment]
I will fix it's tomorrow or today

пт, 27 вер. 2024, 10:18 користувач xxXCuriositykilledthecatXxx <
***@***.***> пише:
