### ISSUE TITLE
Conflict with SleepingOverhaul mod (and its dependent, TickrateChanger mod)

### ISSUE THREAD

**Issue by taisong0612** [KoTeuKa404/thaumicforever#3]
SleepingOverhaul mod has a known incompatiblity with VintageFix concerning this option from mixin:
mixin.bugfix.slow_tps_catchup
is set to true. It prevents server-side tick acceleration.

Now, this mod is also causing incompatibility with SleepingOverhaul. 
I suspect some kind of mixin option is causing problems again.

**Comment by KoTeuKa404** [comment]
try 3.1.4

**Comment by taisong0612** [comment]
Unfortunately, the problem persists.

**Comment by KoTeuKa404** [comment]
i remake 3.1.4 plz try again

**Comment by taisong0612** [comment]
Unfortunately, the problem still persists. 
server side acceleration is still broken.

**Comment by taisong0612** [comment]
4.1 seems to have fixed the issue.
Looks like the mod no longer requires mixinbooter, it must have been the culprit. Closing the case.
