### ISSUE TITLE
Duplicator really can duplicate things

### ISSUE THREAD

**Issue by FantasyShark** [KoTeuKa404/thaumicforever#4]
Stackable items in the craft grids can be doubled by clicking them when pressing Shift.

**Comment by KoTeuKa404** [comment]
try new version

**Comment by FantasyShark** [comment]
Just found that items in inventory can also be duplicated.

**Comment by KoTeuKa404** [comment]
can you send a screenshot?

**Comment by FantasyShark** [comment]
> can you send a screenshot?

It's the same issue. In the Duplicator GUI items can be doubled by clicking them while pressing Shift. The ones in the crafting grids is fixed but those in the inventory are not.
![QQ20241204-113809](https://github.com/user-attachments/assets/623fe3fa-1175-4615-b9aa-96e9a5e38d74)
![QQ20241204-113847](https://github.com/user-attachments/assets/1c3de799-3726-4727-b677-fa010a947c00)

**Comment by KoTeuKa404** [comment]
I fix it, I reload 4.1.6 try it
