### ISSUE TITLE
Unflight Stone still works after being broken by a creative-mode player

### ISSUE THREAD

**Issue by FantasyShark** [KoTeuKa404/thaumicforever#5]
It can be fixed by re-joining the world. I only tested this in a single player save so I don't know how it goes with multiplayer. And I think   players in creative-mode should be immune to this stone.

**Comment by KoTeuKa404** [comment]
ok i fix it later ,u also can switch between mode and fix its

**Comment by KoTeuKa404** [comment]
try 4.1.5

**Comment by FantasyShark** [comment]
> try 4.1.5

Nice job. And I mentioned a new issue in the previous closed duplicator issue. Maybe you can reopen it and give it a look.

**Comment by FantasyShark** [comment]
By the way is the latest version stable? I can translate it to Chinese if the research text won't change a lot in the future.

**Comment by KoTeuKa404** [comment]
hmm, I guess I won't change the text in the future (except the Revive skeleton text),so if u wanna your welcome
