### ISSUE TITLE
Probable crash from worldgen

### ISSUE THREAD

**Issue by taisong0612** [KoTeuKa404/thaumicforever#6]
I installed 5.0 and generated a part of the overworld, and the server crashed. Crash log is attached.
[crash-2024-12-15_17.17.09-server.txt](https://github.com/user-attachments/files/18139433/crash-2024-12-15_17.17.09-server.txt)

**Comment by KoTeuKa404** [comment]
ok,i fix it now

**Comment by taisong0612** [comment]
nice. the crash issue is no more. Quick fingers you got there.
